routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['middleware' => 'auth'], function() {
	/*Route::get('home', [
		'use' => 'HomeController@getHome', 'as' => 'home'
	]);*/
	Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'as' => 'dashboard.'], function() {
		Route::get('home', [
			'uses' => 'DashboardController@getHome', 'as' => 'home'
		]);
		Route::post('change-locale', [
			'uses' => 'UserController@postChangeLocale', 'as' => 'user.change-locale'
		]);

		Route::group(['middleware' => 'access.role:admin'], function() {
			Route::resource('users', 'UserController');
		});
		Route::group(['middleware' => 'access.role:student'], function() {
			Route::get('tasks/student', [
				'uses' => 'TaskController@getStudentIndex', 'as' => 'tasks.get-student-index'
			]);
			Route::get('tasks/student/accepted', [
				'uses' => 'TaskController@getStudentAccepted', 'as' => 'tasks.get-student-accepted'
			]);
			Route::get('tasks/student/show/{id}', [
				'uses' => 'TaskController@show', 'as' => 'tasks.show'
			]);
			Route::post('tasks/{id}/apply', [
				'uses' => 'TaskController@postApply', 'as' => 'tasks.apply'
			]);
			Route::post('tasks/{id}/cancel-apply', [
				'uses' => 'TaskController@postCancelApply', 'as' => 'tasks.cancel-apply'
			]);
		});
		Route::group(['middleware' => 'access.role:teacher'], function() {
			Route::get('tasks/applications', [
				'uses' => 'TaskController@getApplications', 'as' => 'tasks.applications'
			]);
			Route::get('tasks/accepted', [
				'uses' => 'TaskController@getAcceptedApplications', 'as' => 'tasks.accepted-applications'
			]);
			Route::post('tasks/{id}/accept', [
				'uses' => 'TaskController@postAccept', 'as' => 'tasks.accept'
			]);
			Route::post('tasks/{id}/cancel-accept', [
				'uses' => 'TaskController@postCancelAccept', 'as' => 'tasks.cancel-accept'
			]);
			Route::resource('tasks', 'TaskController', ['except' => [
			    'show'
			]]);
		});
	});
});

Auth::routes();

app/Models/User/User.php
<?php

namespace App\Models\User;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    protected $with = ['roles'];

    public function roles() {
        return $this->belongsToMany(\App\Models\Role\Role::class, 'user_role');
    }

    public function tasks() {
        return $this->hasMany(\App\Models\Task\Task::class);
    }

    public function applications() {
        return $this->belongsToMany(\App\Models\Task\Task::class, 'student_task');
    }

    public function hasRole($role) {
        return (count($this->roles->filter(function($item) use($role) { 
            return $item->key == $role;
        })) > 0) ? true : false;
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User\User;
use App\Models\Role\Role;

class UserController extends Controller
{
    public function postChangeLocale(Request $request) {
        $user = auth()->user();
        $user->locale = $request->input('locale');
        $user->save();
        \App::setLocale($request->input('locale'));
        
        return redirect()->back();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('roles', 'tasks')->get();

        return view('dashboard.layouts.users.index', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::with('roles')->find($id);
        $roles = Role::all()->pluck('name', 'id');
        $selectedRoles = $user->roles->pluck('id')->toArray();
        return view('dashboard.layouts.users.edit', [
            'user' => $user,
            'roles' => $roles,
            'selectedRoles' => $selectedRoles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $roles = [];
        if ($request->input('roles') != null) {
            $roles = $request->input('roles');
        }
        $user->roles()->sync($roles);
        $user->update($request->all());

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/layouts/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Users</div>

                <div class="panel-body">
                	{!! Form::model($user, ['method' => 'PUT', 'route' => ['dashboard.users.update', $user->id]]) !!}
                        @include('dashboard.layouts.users.includes.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/layouts/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Users</div>

                <div class="panel-body">
                	<table class="table table-hover">
                		<thead>
                			<tr>
                				<th>Name</th>
                				<th>Email</th>
                				<th>Roles</th>
                				<th>Actions</th>
                			</tr>
                		</thead>
                		<tbody>
                			@foreach($users as $user)
		                    	<tr>
	                				<td>{{ $user->name }}</td>
	                				<td>{{ $user->email }}</td>
	                				<td>
	                					@foreach($user->roles as $role)
	                						<span class="label label-info">{{ $role->name }}</span>
	                					@endforeach
	                				</td>
	                				<td><a href="{{ route('dashboard.users.edit', $user->id) }}" class="btn btn-xs btn-primary">Edit</a></td>
	                			</tr>
		                    @endforeach
                		</tbody>
                	</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection