routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['middleware' => 'auth'], function() {
	/*Route::get('home', [
		'use' => 'HomeController@getHome', 'as' => 'home'
	]);*/
	Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'as' => 'dashboard.'], function() {
		Route::get('home', [
			'uses' => 'DashboardController@getHome', 'as' => 'home'
		]);
		Route::post('change-locale', [
			'uses' => 'UserController@postChangeLocale', 'as' => 'user.change-locale'
		]);

		Route::group(['middleware' => 'access.role:admin'], function() {
			Route::resource('users', 'UserController');
		});
		Route::group(['middleware' => 'access.role:student'], function() {
			Route::get('tasks/student', [
				'uses' => 'TaskController@getStudentIndex', 'as' => 'tasks.get-student-index'
			]);
			Route::get('tasks/student/accepted', [
				'uses' => 'TaskController@getStudentAccepted', 'as' => 'tasks.get-student-accepted'
			]);
			Route::get('tasks/student/show/{id}', [
				'uses' => 'TaskController@show', 'as' => 'tasks.show'
			]);
			Route::post('tasks/{id}/apply', [
				'uses' => 'TaskController@postApply', 'as' => 'tasks.apply'
			]);
			Route::post('tasks/{id}/cancel-apply', [
				'uses' => 'TaskController@postCancelApply', 'as' => 'tasks.cancel-apply'
			]);
		});
		Route::group(['middleware' => 'access.role:teacher'], function() {
			Route::get('tasks/applications', [
				'uses' => 'TaskController@getApplications', 'as' => 'tasks.applications'
			]);
			Route::get('tasks/accepted', [
				'uses' => 'TaskController@getAcceptedApplications', 'as' => 'tasks.accepted-applications'
			]);
			Route::post('tasks/{id}/accept', [
				'uses' => 'TaskController@postAccept', 'as' => 'tasks.accept'
			]);
			Route::post('tasks/{id}/cancel-accept', [
				'uses' => 'TaskController@postCancelAccept', 'as' => 'tasks.cancel-accept'
			]);
			Route::resource('tasks', 'TaskController', ['except' => [
			    'show'
			]]);
		});
	});
});

Auth::routes();

app/Models/Task/Task.php
<?php

namespace App\Models\Task;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
	protected $fillable = [
        'title', 'task', 'study_type'
    ];

    public function user() {
    	return $this->belongsTo(\App\Models\User\User::class);
    }

    public function student() {
    	return $this->belongsTo(\App\Models\User\User::class, 'student_id');
    }

    public function applicants() {
    	return $this->belongsToMany(\App\Models\User\User::class, 'student_task');
    }

    public function getStudyTypeAttribute($value) {
    	$studyType = array_first(config('constants.study_types'), function($v, $k) use($value) {
    		return $k == $value;
    	});
    	return $studyType;
    }

    public function getTitleAttribute($value) {
    	if (auth()->user()->locale == 'en') {
    		return $this->title_en;
    	}
    	return $value;
    }

    public function getTaskAttribute($value) {
    	if (auth()->user()->locale == 'en') {
    		return $this->task_en;
    	}
    	return $value;
    }

    public function scopeAvailable($query) {
    	return $query->whereNull('student_id');
    }

    public function scopeAcceptedForUser($query, $userId) {
    	return $query->where('student_id', $userId);
    }
}

app/Http/Controllers/Dashboard/TaskController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Task\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = auth()->user()->tasks()->with('student', 'applicants')->get();

        return view('dashboard.layouts.tasks.index', [
            'tasks' => $tasks
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $studyTypes = config('constants.study_types');
        return view('dashboard.layouts.tasks.create', [
            'studyTypes' => $studyTypes
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        auth()->user()->tasks()->create($request->all());
        return redirect()->route('dashboard.tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::find($id);
        return view('dashboard.layouts.tasks.show', [
            'task' => $task
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $studyTypes = config('constants.study_types');
        $task = Task::find($id);
        return view('dashboard.layouts.tasks.edit', [
            'task' => $task,
            'studyTypes' => $studyTypes
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        auth()->user()->tasks()->find($id)->update($request->all());
        return redirect()->route('dashboard.tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getStudentIndex() {
        $tasks = Task::available()->with('applicants')->get();
        $userTasks = auth()->user()->applications()->get();

        return view('dashboard.layouts.tasks.index', [
            'tasks' => $tasks,
            'userTasks' => $userTasks
        ]);
    }

    public function getStudentAccepted() {
        $tasks = Task::acceptedForUser(auth()->user()->id)->get();

        return view('dashboard.layouts.tasks.accepted', [
            'tasks' => $tasks
        ]);
    }

    public function getApplications() {
        $applications = auth()->user()->tasks()->whereNull('student_id')->with('applicants')->has('applicants')->get();

        return view('dashboard.layouts.tasks.applications', [
            'tasks' => $applications
        ]);
    }

    public function getAcceptedApplications() {
        $applications = auth()->user()->tasks()->with('applicants', 'student')->whereNotNull('student_id')->get();

        return view('dashboard.layouts.tasks.accepted', [
            'tasks' => $applications
        ]);
    }

    public function postApply(Request $request, $taskId) {
        $user = auth()->user();
        $user->applications()->attach($taskId);
        return redirect()->back();
    }

    public function postCancelApply(Request $request, $taskId) {
        $user = auth()->user();
        $user->applications()->detach($taskId);
        return redirect()->back();
    }

    public function postAccept(Request $request, $taskId) {
        $task = Task::with('applicants')->find($taskId);
        $applicantId = $request->input('student');
        $task->student_id = $applicantId;
        $task->save();
        return redirect()->back();
    }

    public function postCancelAccept(Request $request, $taskId) {
        $task = Task::find($taskId);
        $task->student_id = null;
        $task->save();
        return redirect()->back();
    }
}

resources/views/dashboard/layouts/tasks/accepted.blade.php
@extends('layouts.app')

@section('content')

@if(auth()->user()->hasRole('teacher'))
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Applications</div>

                    <div class="panel-body">
                    	<table class="table table-hover">
                    		<thead>
                    			<tr>
                    				<th>Title</th>
                    				<th>Task assignment</th>
                    				<th>Study type</th>
                                    <th>Student</th>
                    				<th>Actions</th>
                    			</tr>
                    		</thead>
                    		<tbody>
                    			@foreach($tasks as $task)
    		                    	<tr>
    	                				<td>{{ $task->title }}</td>
    	                				<td>{{ str_limit($task->task, 50, "...") }}</td>
    	                				<td><span class="label label-info">{{ $task->study_type }}</span></td>
                                        <td>{{ $task->student->name }}</td>
    	                				<td>
                                            <a href="{{ route('dashboard.tasks.edit', $task->id) }}" class="btn btn-xs btn-primary">Edit</a>
                                            {!! Form::open(['route' => ['dashboard.tasks.cancel-accept', $task->id]]) !!}
                                                {!! Form::submit('Cancel', ['class' => 'btn btn-xs btn-danger']) !!}
                                            {!! Form::close() !!}
                                        </td>
    	                			</tr>
    		                    @endforeach
                    		</tbody>
                    	</table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif
@if(auth()->user()->hasRole('student'))
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Accepted Tasks</div>

                    <div class="panel-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Task assignment</th>
                                    <th>Study type</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tasks as $task)
                                    <tr>
                                        <td>{{ $task->title }}</td>
                                        <td>{{ str_limit($task->task, 50, "...") }}</td>
                                        <td><span class="label label-info">{{ $task->study_type }}</span></td>
                                        <td>
                                            <a href="{{ route('dashboard.tasks.show', $task->id) }}" class="btn btn-xs btn-info">View</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

@endsection

resources/views/dashboard/layouts/tasks/applications.blade.php
@extends('layouts.app')

@section('content')

@if(auth()->user()->hasRole('teacher'))
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Applications</div>

                    <div class="panel-body">
                    	<table class="table table-hover">
                    		<thead>
                    			<tr>
                    				<th>Title</th>
                    				<th>Task assignment</th>
                    				<th>Study type</th>
                                    <th>Applicants</th>
                    				<th>Actions</th>
                    			</tr>
                    		</thead>
                    		<tbody>
                    			@foreach($tasks as $task)
    		                    	<tr>
    	                				<td>{{ $task->title }}</td>
    	                				<td>{{ str_limit($task->task, 50, "...") }}</td>
    	                				<td><span class="label label-info">{{ $task->study_type }}</span></td>
                                        <td>
                                            @foreach($task->applicants as $applicant)
                                                {{ $applicant->name }}<br>
                                            @endforeach
                                        </td>
    	                				<td>
                                            {!! Form::open(['route' => ['dashboard.tasks.accept', $task->id]]) !!}
                                                {!! Form::select('student', $task->applicants->pluck('name', 'id'), null, ['class' => 'form-control']) !!}
                                                {!! Form::submit('Accept', ['class' => 'btn btn-xs btn-primary']) !!}
                                            {!! Form::close() !!}
                                        </td>
    	                			</tr>
    		                    @endforeach
                    		</tbody>
                    	</table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

@endsection

resources/views/dashboard/layouts/tasks/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">New Task</div>

                <div class="panel-body">
                	{!! Form::open(['route' => 'dashboard.tasks.store']) !!}
                        @include('dashboard.layouts.tasks.includes.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/layouts/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">New Task</div>

                <div class="panel-body">
                	{!! Form::model($task, ['method' => 'PUT', 'route' => ['dashboard.tasks.update', $task->id]]) !!}
                        @include('dashboard.layouts.tasks.includes.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/layouts/tasks/index.blade.php
@extends('layouts.app')

@section('content')

@if(auth()->user()->hasRole('teacher'))
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">My Tasks</div>

                    <div class="panel-body">
                    	<table class="table table-hover">
                    		<thead>
                    			<tr>
                    				<th>Title</th>
                    				<th>Task assignment</th>
                    				<th>Study type</th>
                                    <th>Accepted</th>
                                    <th>Applicants</th>
                    				<th>Actions</th>
                    			</tr>
                    		</thead>
                    		<tbody>
                    			@foreach($tasks as $task)
    		                    	<tr>
    	                				<td>{{ $task->title }}</td>
    	                				<td>{{ str_limit($task->task, 50, "...") }}</td>
    	                				<td><span class="label label-info">{{ $task->study_type }}</span></td>
                                        <td>{{ ($task->student == null) ? 'NO' : 'YES' }}</td>
                                        <td><span class="label label-primary">{{ $task->applicants->count() }}</span></td>
    	                				<td><a href="{{ route('dashboard.tasks.edit', $task->id) }}" class="btn btn-xs btn-primary">Edit</a></td>
    	                			</tr>
    		                    @endforeach
                    		</tbody>
                    	</table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif
@if(auth()->user()->hasRole('student'))
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Available Tasks</div>

                    <div class="panel-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Task assignment</th>
                                    <th>Study type</th>
                                    <th>Teacher</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tasks as $task)
                                    <tr>
                                        <td>{{ $task->title }}</td>
                                        <td>{{ str_limit($task->task, 50, "...") }}</td>
                                        <td><span class="label label-info">{{ $task->study_type }}</span></td>
                                        <td><span class="label label-default">{{ $task->user->name }}</span></td>
                                        <td>
                                            @if(count($userTasks->where('id', $task->id)) > 0)
                                                {!! Form::open(['route' => ['dashboard.tasks.cancel-apply', $task->id]]) !!}
                                                    {!! Form::submit('Cancel', ['class' => 'btn btn-xs btn-danger']) !!}
                                                {!! Form::close() !!}
                                            @else
                                                {!! Form::open(['route' => ['dashboard.tasks.apply', $task->id]]) !!}
                                                    {!! Form::submit('Apply', ['class' => 'btn btn-xs btn-primary']) !!}
                                                {!! Form::close() !!}
                                            @endif
                                            <a href="{{ route('dashboard.tasks.show', $task->id) }}" class="btn btn-xs btn-info">View</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

@endsection

resources/views/dashboard/layouts/tasks/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Task</div>

                <div class="panel-body">
                	<div class="row">
                        <div class="col-sm-6">
                            <div class="well">
                                <h3 style="margin: 0 0 10px 0;">Title</h3>
                                {{ $task->title }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="well">
                                <h3 style="margin: 0 0 10px 0;">Assignment</h3>
                                {{ $task->task }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection